---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: centos/7
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: firewalld
verifier:
  name: goss
  lint:
    name: yamllint
