---
- name: Enable iptables rules
  iptables_raw:
    rules: "-A {{ item[1].chain }} -p tcp --dport {{ item[0].value }} -m conntrack --ctstate {{ item[1].ctstate }} -j ACCEPT"
    name: "Allow {{ item[1].chain }} for port {{ item[0].value }}"
  with_nested:
    - [ { value: "{{ proxy_socks_port }}", if: "{{ proxy_socks }}" }, { value: "{{ proxy_http_port }}", if: "{{ proxy_http }}" } ]
    - [ { ctstate: "NEW,ESTABLISHED", chain: "INPUT", }, { ctstate: "ESTABLISHED", chain: "OUTPUT" } ]
  when: item[0].if
