---
- name: gather os specific variables
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: get info about 3proxy service
  systemd:
    name: 3proxy.service
    enabled: true
  when: ansible_service_mgr == 'systemd'
  register: proxy_info

- name: Set log directory writable for 3proxy if needed
  ini_file:
    path: "{{ proxy_info.status.FragmentPath }}"
    section: Service
    option: ReadWritePaths
    value: /var/log/3proxy
  when: ansible_service_mgr == 'systemd'
  notify: reload service

- name: Ensures 3proxy service is started and enabled
  service:
    name: 3proxy
    enabled: true
    state: started
  ignore_errors: true
