---
- name: Ensures 3proxy PPA is added
  apt_repository:
    repo: ppa:artyom.h31/3proxy

- name: Ensures 3proxy is installed
  apt:
    name: 3proxy
    update_cache: true

- name: Ensures 3proxy log dir exists
  file:
    name: /var/log/3proxy
    state: directory
    owner: nobody
    group: nogroup

- name: Configures 3proxy
  template:
    src: 3proxy.cfg.j2
    dest: /etc/3proxy/3proxy.cfg
    owner: nobody
    group: nogroup
  notify: "reload service"
