---
- name: Ensures 3proxy PPA is added
  apt_repository:
    repo: ppa:artyom.h31/3proxy

- name: Ensures 3proxy is installed
  apt:
    name: 3proxy

- name: Ensures 3proxy log dir exists
  file:
    name: /var/log/3proxy
    state: directory
    owner: nobody
    group: nogroup

- name: Configures 3proxy
  template:
    src: 3proxy.cfg.j2
    dest: /etc/3proxy/3proxy.cfg
    owner: nobody
    group: nogroup
  register: config_changed

- name: Ensures 3proxy service is started and enabled
  service:
    name: 3proxy
    enabled: true
    state: started
  ignore_errors: true

- name: Ensures 3proxy service config is up to date
  service:
    name: 3proxy
    state: restarted
  when: config_changed.changed
