---
- name: ufw - enable forwarding
  lineinfile:
    dest: /etc/default/ufw
    regexp: "^DEFAULT_FORWARD_POLICY="
    line: DEFAULT_FORWARD_POLICY="ACCEPT"

- name: ufw - Allow incoming VPN connection
  ufw:
    direction: in
    proto: tcp
    to_port: "{{ item.item }}"
    rule: allow
  when: item.if
  with_items:
    - { item: "{{ proxy_socks_port }}", if: "{{ proxy_socks }}" }
    - { item: "{{ proxy_http_port }}", if: "{{ proxy_http }}" }
