---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance-1
    config_options:
      synced_folder: true
    box: centos/6
    memory: 1024
    cpus: 1
    provision: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: iptables
verifier:
  name: goss
  lint:
    name: yamllint
