---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: none
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: iptables
verifier:
  name: testinfra
  lint:
    name: flake8
